version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/portfolio/
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
    - location: scripts/bootstrap_ec2.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/applicationstart.sh
      timeout: 180
      runas: root
  ApplicationStop:
    - location: scripts/applicationstop.sh
      timeout: 300
      runas: root